export global AppTheme {
    in-out property <color> bg: #ecfbf4;
    in-out property <color> panel: #ffffff;
    in-out property <color> panel-soft: #e9f8f0;
    in-out property <color> border: #ccebdd;
    in-out property <color> text: #07130f;
    in-out property <color> muted: #50625b;
    in-out property <color> weak: #8da096;
    in-out property <color> accent: #00d982;
    in-out property <color> accent-dark: #06b96f;
    in-out property <color> danger: #ef6969;
    in-out property <color> warning: #f5a524;
    in-out property <color> success: #00c878;
}
