import { ThumbnailCard } from "thumbnail-card.slint";
import { AssetItem } from "../types.slint";

export component WaterfallColumn {
    in property <[AssetItem]> items;
    in property <length> card-width: 220px;
    in property <string> source: "inspiration";
    in property <int> column-index: 0;
    in property <int> column-count: 1;
    horizontal-stretch: 0;
    width: root.column-width();
    height: content.preferred-height;
    content := VerticalLayout {
        x: 0px;
        width: root.width;
        spacing: 0px;
        alignment: start;
        for _[index] in root.column-length(): ThumbnailCard {
            item: root.items[root.source-index(index)];
            card-width: root.card-width;
            card-gap: 18px;
            source: root.source;
            masonry: true;
        }
    }
    function column-width() -> length {
        return root.card-width;
    }
    function column-length() -> int {
        if root.items.length <= root.column-index {
            return 0;
        }
        return floor((root.items.length - 1 - root.column-index) / root.column-count) + 1;
    }
    function source-index(index: int) -> int {
        return index * root.column-count + root.column-index;
    }
}
